
# Hibernate & Mail Configs
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://mysql-22ae2abd-ou-b8aa.l.aivencloud.com:21201/online_clinic?sslMode=REQUIRED&useSSL=true
hibernate.connection.username=avnadmin
hibernate.connection.password=AVNS_TyRiS9mAluH0QoEF-8o
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true
mail.host=smtp.gmail.com
mail.port=587
mail.username=vonguyenhung567@gmail.com
mail.password=zdmjwypcjauzojab

# VNPay Sandbox Configs
vnp.tmn_code=2QXU0HL7
vnp.hash_secret=G8SNG6U0T67S4B9V8M6K9V2U9M6S6K8O
vnp.pay_url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return_url=http://localhost:3000/payment-result
vnp.api_url=https://sandbox.vnpayment.vn/merchant_webapi/api.py
