
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://mysql-22ae2abd-ou-b8aa.l.aivencloud.com:21201/online_clinic?sslMode=REQUIRED&useSSL=true
hibernate.connection.username=avnadmin
hibernate.connection.password=AVNS_TyRiS9mAluH0QoEF-8o
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true
mail.host=smtp.gmail.com
mail.port=587
mail.username=vonguyenhung567@gmail.com
mail.password=zdmjwypcjauzojab